# Generated by Django 3.0.1 on 2020-01-11 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album_photo', '0002_photo_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='description',
            field=models.CharField(default='default description', max_length=500),
            preserve_default=False,
        ),
    ]
