# Generated by Django 3.0.1 on 2020-01-11 20:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('album_photo', '0003_photo_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('author', models.ManyToManyField(related_name='author_comments', to=settings.AUTH_USER_MODEL)),
                ('photo', models.ManyToManyField(related_name='photo_comments', to='album_photo.Photo')),
            ],
        ),
    ]
